services:
  - type: web
    name: careerbuddy-backend
    runtime: python
    repo: https://github.com/sivasurya681/careerbuddy-ai
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false